edge:
  - headers:
      - key: Cross-Origin-Opener-Policy
        value: same-origin
      - key: Cross-Origin-Embedder-Policy
        value: require-corp
      - key: Accept-Ranges
        value: bytes
